using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Menu_ConvertSpriteFromCardNo : MonoBehaviour
{
    public List<Sprite> TheFirstChapterList = new List<Sprite> ();
    public Sprite noImage;

    public Sprite ConvertSpriteFromCardNo(string paramater)
    {
        switch (paramater)
        {
            case "001_JA_01":
                return TheFirstChapterList[0];
            case "002_JA_01":
                return TheFirstChapterList[1];
            case "003_JA_01":
                return TheFirstChapterList[2];
            case "004_JA_01":
                return TheFirstChapterList[3];
            case "005_JA_01":
                return TheFirstChapterList[4];
            case "006_JA_01":
                return TheFirstChapterList[5];
            case "007_JA_01":
                return TheFirstChapterList[6];
            case "008_JA_01":
                return TheFirstChapterList[7];
            case "009_JA_01":
                return TheFirstChapterList[8];
            case "010_JA_01":
                return TheFirstChapterList[9];
            case "011_JA_01":
                return TheFirstChapterList[10];
            case "012_JA_01":
                return TheFirstChapterList[11];
            case "013_JA_01":
                return TheFirstChapterList[12];
            case "014_JA_01":
                return TheFirstChapterList[13];
            case "015_JA_01":
                return TheFirstChapterList[14];
            case "016_JA_01":
                return TheFirstChapterList[15];
            case "017_JA_01":
                return TheFirstChapterList[16];
            case "018_JA_01":
                return TheFirstChapterList[17];
            case "019_JA_01":
                return TheFirstChapterList[18];
            case "020_JA_01":
                return TheFirstChapterList[19];
            case "021_JA_01":
                return TheFirstChapterList[20];
            case "022_JA_01":
                return TheFirstChapterList[21];
            case "023_JA_01":
                return TheFirstChapterList[22];
            case "024_JA_01":
                return TheFirstChapterList[23];
            case "025_JA_01":
                return TheFirstChapterList[24];
            case "026_JA_01":
                return TheFirstChapterList[25];
            case "027_JA_01":
                return TheFirstChapterList[26];
            case "028_JA_01":
                return TheFirstChapterList[27];
            case "029_JA_01":
                return TheFirstChapterList[28];
            case "030_JA_01":
                return TheFirstChapterList[29];
            case "031_JA_01":
                return TheFirstChapterList[30];
            case "032_JA_01":
                return TheFirstChapterList[31];
            case "033_JA_01":
                return TheFirstChapterList[32];
            case "034_JA_01":
                return TheFirstChapterList[33];
            case "035_JA_01":
                return TheFirstChapterList[34];
            case "036_JA_01":
                return TheFirstChapterList[35];
            case "037_JA_01":
                return TheFirstChapterList[36];
            case "038_JA_01":
                return TheFirstChapterList[37];
            case "039_JA_01":
                return TheFirstChapterList[38];
            case "040_JA_01":
                return TheFirstChapterList[39];
            case "041_JA_01":
                return TheFirstChapterList[40];
            case "042_JA_01":
                return TheFirstChapterList[41];
            case "043_JA_01":
                return TheFirstChapterList[42];
            case "044_JA_01":
                return TheFirstChapterList[43];
            case "045_JA_01":
                return TheFirstChapterList[44];
            case "046_JA_01":
                return TheFirstChapterList[45];
            case "047_JA_01":
                return TheFirstChapterList[46];
            case "048_JA_01":
                return TheFirstChapterList[47];
            case "049_JA_01":
                return TheFirstChapterList[48];
            case "050_JA_01":
                return TheFirstChapterList[49];
            case "051_JA_01":
                return TheFirstChapterList[50];
            case "052_JA_01":
                return TheFirstChapterList[51];
            case "053_JA_01":
                return TheFirstChapterList[52];
            case "054_JA_01":
                return TheFirstChapterList[53];
            case "055_JA_01":
                return TheFirstChapterList[54];
            case "056_JA_01":
                return TheFirstChapterList[55];
            case "057_JA_01":
                return TheFirstChapterList[56];
            case "058_JA_01":
                return TheFirstChapterList[57];
            case "059_JA_01":
                return TheFirstChapterList[58];
            case "060_JA_01":
                return TheFirstChapterList[59];
            case "061_JA_01":
                return TheFirstChapterList[60];
            case "062_JA_01":
                return TheFirstChapterList[61];
            case "063_JA_01":
                return TheFirstChapterList[62];
            case "064_JA_01":
                return TheFirstChapterList[63];
            case "065_JA_01":
                return TheFirstChapterList[64];
            case "066_JA_01":
                return TheFirstChapterList[65];
            case "067_JA_01":
                return TheFirstChapterList[66];
            case "068_JA_01":
                return TheFirstChapterList[67];
            case "069_JA_01":
                return TheFirstChapterList[68];
            case "070_JA_01":
                return TheFirstChapterList[69];
            case "071_JA_01":
                return TheFirstChapterList[70];
            case "072_JA_01":
                return TheFirstChapterList[71];
            case "073_JA_01":
                return TheFirstChapterList[72];
            case "074_JA_01":
                return TheFirstChapterList[73];
            case "075_JA_01":
                return TheFirstChapterList[74];
            case "076_JA_01":
                return TheFirstChapterList[75];
            case "077_JA_01":
                return TheFirstChapterList[76];
            case "078_JA_01":
                return TheFirstChapterList[77];
            case "079_JA_01":
                return TheFirstChapterList[78];
            case "080_JA_01":
                return TheFirstChapterList[79];
            case "081_JA_01":
                return TheFirstChapterList[80];
            case "082_JA_01":
                return TheFirstChapterList[81];
            case "083_JA_01":
                return TheFirstChapterList[82];
            case "084_JA_01":
                return TheFirstChapterList[83];
            case "085_JA_01":
                return TheFirstChapterList[84];
            case "086_JA_01":
                return TheFirstChapterList[85];
            case "087_JA_01":
                return TheFirstChapterList[86];
            case "088_JA_01":
                return TheFirstChapterList[87];
            case "089_JA_01":
                return TheFirstChapterList[88];
            case "090_JA_01":
                return TheFirstChapterList[89];
            case "091_JA_01":
                return TheFirstChapterList[90];
            case "092_JA_01":
                return TheFirstChapterList[91];
            case "093_JA_01":
                return TheFirstChapterList[92];
            case "094_JA_01":
                return TheFirstChapterList[93];
            case "095_JA_01":
                return TheFirstChapterList[94];
            case "096_JA_01":
                return TheFirstChapterList[95];
            case "097_JA_01":
                return TheFirstChapterList[96];
            case "098_JA_01":
                return TheFirstChapterList[97];
            case "099_JA_01":
                return TheFirstChapterList[98];
            case "100_JA_01":
                return TheFirstChapterList[99];
            case "101_JA_01":
                return TheFirstChapterList[100];
            case "102_JA_01":
                return TheFirstChapterList[101];
            case "103_JA_01":
                return TheFirstChapterList[102];
            case "104_JA_01":
                return TheFirstChapterList[103];
            case "105_JA_01":
                return TheFirstChapterList[104];
            case "106_JA_01":
                return TheFirstChapterList[105];
            case "107_JA_01":
                return TheFirstChapterList[106];
            case "108_JA_01":
                return TheFirstChapterList[107];
            case "109_JA_01":
                return TheFirstChapterList[108];
            case "110_JA_01":
                return TheFirstChapterList[109];
            case "111_JA_01":
                return TheFirstChapterList[110];
            case "112_JA_01":
                return TheFirstChapterList[111];
            case "113_JA_01":
                return TheFirstChapterList[112];
            case "114_JA_01":
                return TheFirstChapterList[113];
            case "115_JA_01":
                return TheFirstChapterList[114];
            case "116_JA_01":
                return TheFirstChapterList[115];
            case "117_JA_01":
                return TheFirstChapterList[116];
            case "118_JA_01":
                return TheFirstChapterList[117];
            case "119_JA_01":
                return TheFirstChapterList[118];
            case "120_JA_01":
                return TheFirstChapterList[119];
            case "121_JA_01":
                return TheFirstChapterList[120];
            case "122_JA_01":
                return TheFirstChapterList[121];
            case "123_JA_01":
                return TheFirstChapterList[122];
            case "124_JA_01":
                return TheFirstChapterList[123];
            case "125_JA_01":
                return TheFirstChapterList[124];
            case "126_JA_01":
                return TheFirstChapterList[125];
            case "127_JA_01":
                return TheFirstChapterList[126];
            case "128_JA_01":
                return TheFirstChapterList[127];
            case "129_JA_01":
                return TheFirstChapterList[128];
            case "130_JA_01":
                return TheFirstChapterList[129];
            case "131_JA_01":
                return TheFirstChapterList[130];
            case "132_JA_01":
                return TheFirstChapterList[131];
            case "133_JA_01":
                return TheFirstChapterList[132];
            case "134_JA_01":
                return TheFirstChapterList[133];
            case "135_JA_01":
                return TheFirstChapterList[134];
            case "136_JA_01":
                return TheFirstChapterList[135];
            case "137_JA_01":
                return TheFirstChapterList[136];
            case "138_JA_01":
                return TheFirstChapterList[137];
            case "139_JA_01":
                return TheFirstChapterList[138];
            case "140_JA_01":
                return TheFirstChapterList[139];
            case "141_JA_01":
                return TheFirstChapterList[140];
            case "142_JA_01":
                return TheFirstChapterList[140];
            case "143_JA_01":
                return TheFirstChapterList[140];
            case "144_JA_01":
                return TheFirstChapterList[140];
            case "145_JA_01":
                return TheFirstChapterList[140];
            case "146_JA_01":
                return TheFirstChapterList[140];
            case "147_JA_01":
                return TheFirstChapterList[140];
            case "148_JA_01":
                return TheFirstChapterList[140];
            case "149_JA_01":
                return TheFirstChapterList[140];
            case "150_JA_01":
                return TheFirstChapterList[140];
            case "151_JA_01":
                return TheFirstChapterList[150];
            case "152_JA_01":
                return TheFirstChapterList[151];
            case "153_JA_01":
                return TheFirstChapterList[152];
            case "154_JA_01":
                return TheFirstChapterList[153];
            case "155_JA_01":
                return TheFirstChapterList[154];
            case "156_JA_01":
                return TheFirstChapterList[155];
            case "157_JA_01":
                return TheFirstChapterList[156];
            case "158_JA_01":
                return TheFirstChapterList[157];
            case "159_JA_01":
                return TheFirstChapterList[158];
            case "160_JA_01":
                return TheFirstChapterList[159];
            case "161_JA_01":
                return TheFirstChapterList[160];
            case "162_JA_01":
                return TheFirstChapterList[161];
            case "163_JA_01":
                return TheFirstChapterList[162];
            case "164_JA_01":
                return TheFirstChapterList[163];
            case "165_JA_01":
                return TheFirstChapterList[164];
            case "166_JA_01":
                return TheFirstChapterList[165];
            case "167_JA_01":
                return TheFirstChapterList[166];
            case "168_JA_01":
                return TheFirstChapterList[167];
            case "169_JA_01":
                return TheFirstChapterList[168];
            case "170_JA_01":
                return TheFirstChapterList[169];
            case "171_JA_01":
                return TheFirstChapterList[170];
            case "172_JA_01":
                return TheFirstChapterList[171];
            case "173_JA_01":
                return TheFirstChapterList[172];
            case "174_JA_01":
                return TheFirstChapterList[173];
            case "175_JA_01":
                return TheFirstChapterList[174];
            case "176_JA_01":
                return TheFirstChapterList[175];
            case "177_JA_01":
                return TheFirstChapterList[176];
            case "178_JA_01":
                return TheFirstChapterList[177];
            case "179_JA_01":
                return TheFirstChapterList[178];
            case "180_JA_01":
                return TheFirstChapterList[179];
            case "181_JA_01":
                return TheFirstChapterList[180];
            case "182_JA_01":
                return TheFirstChapterList[181];
            case "183_JA_01":
                return TheFirstChapterList[182];
            case "184_JA_01":
                return TheFirstChapterList[183];
            case "185_JA_01":
                return TheFirstChapterList[184];
            case "186_JA_01":
                return TheFirstChapterList[185];
            case "187_JA_01":
                return TheFirstChapterList[186];
            case "188_JA_01":
                return TheFirstChapterList[187];
            case "189_JA_01":
                return TheFirstChapterList[188];
            case "190_JA_01":
                return TheFirstChapterList[189];
            case "191_JA_01":
                return TheFirstChapterList[190];
            case "192_JA_01":
                return TheFirstChapterList[191];
            case "193_JA_01":
                return TheFirstChapterList[192];
            case "194_JA_01":
                return TheFirstChapterList[193];
            case "195_JA_01":
                return TheFirstChapterList[194];
            case "196_JA_01":
                return TheFirstChapterList[195];
            case "197_JA_01":
                return TheFirstChapterList[196];
            case "198_JA_01":
                return TheFirstChapterList[197];
            case "199_JA_01":
                return TheFirstChapterList[198];
            case "200_JA_01":
                return TheFirstChapterList[199];
            case "201_JA_01":
                return TheFirstChapterList[200];
            case "202_JA_01":
                return TheFirstChapterList[201];
            case "203_JA_01":
                return TheFirstChapterList[202];
            case "204_JA_01":
                return TheFirstChapterList[203];
            case "205_JA_01":
                return TheFirstChapterList[204];
            case "206_JA_01":
                return TheFirstChapterList[205];
            case "207_JA_01":
                return TheFirstChapterList[206];
            case "208_JA_01":
                return TheFirstChapterList[207];
            case "209_JA_01":
                return TheFirstChapterList[208];
            case "210_JA_01":
                return TheFirstChapterList[209];
            case "211_JA_01":
                return TheFirstChapterList[210];
            case "212_JA_01":
                return TheFirstChapterList[211];
            case "213_JA_01":
                return TheFirstChapterList[212];
            case "214_JA_01":
                return TheFirstChapterList[213];
            case "215_JA_01":
                return TheFirstChapterList[214];
            default:
                return noImage;
        }
    }
}
